"""empty message

Revision ID: 0ce9bc681888
Revises: ad0837f7c9c5
Create Date: 2023-08-30 18:10:36.434749

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '0ce9bc681888'
down_revision: Union[str, None] = 'ad0837f7c9c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exchange_rates',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.Column('from_currency', sa.String(), nullable=False),
                    sa.Column('to_currency', sa.String(), nullable=False),
                    sa.Column('rate', sa.Float(), nullable=False),
                    sa.Column('source', sa.String(), nullable=True),
                    sa.Column('bank_name', sa.String(), nullable=True),
                    sa.Column('buy_rate', sa.Float(), nullable=True),
                    sa.Column('sell_rate', sa.Float(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('exchange_rates')
    # ### end Alembic commands ###
